# Generated by Django 5.1 on 2025-03-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoping',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='shoping',
            name='p_date',
            field=models.CharField(max_length=100),
        ),
    ]
