# Generated by Django 5.1.7 on 2025-04-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_shoping_status_alter_shoping_p_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
