# Generated by Django 5.1 on 2025-03-15 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('feature', models.CharField(max_length=255)),
                ('status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('c_info', models.CharField(max_length=255, null=True)),
                ('image', models.FileField(upload_to='uploads/companys/')),
                ('status', models.BooleanField(null=True)),
                ('types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.categorys')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('des', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='uploads/products/')),
                ('Product_Quantity', models.IntegerField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.categorys')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.companys')),
            ],
        ),
    ]
